id: P56D669D1
initial_creation_type: input
source_metadata:
  title: Mahāmudrā Series
  language: es
  description: 'Lotsawa House presents the following texts on the subject of Mahāmudrā
    (phyag chen) or the ''Great Seal'':'
  volume:
    72d587ff16784289af394ae9a843265d:
      title: Memorandum on the Subject of Mahāmudrā and Dzogchen Instructions
      parent: Advice
    0cf0ef67771c43e1abcddacccccdf6e1:
      title: Mahāmudrā Preliminaries, Main Part & Conclusion
      parent: Advice
    515d82e9c452441696e4f51197b930c0:
      title: 'Mahāmudrā: the Swift Way to Become a Lord of Realization'
      parent: Advice
    0ca71411807d4223a326b63b40fd3a63:
      title: The Kusāli's Instruction on the Nature of Mind
      parent: Advice
    0cbe068517ac48d9b67d50ca24c97b42:
      title: A Way of Settling into the Realization of Mind’s Essence
      parent: Advice
    e17f73ed7c154d918292eb0454f1c9c4:
      title: 'From the Mahāmudrā Preliminary Practices: Continuous Integration with
        Ground, Path, and Fruition'
      parent: Advice
    69517bbdc2fa4c72b0421b059f2dc0ca:
      title: 'Naturally Liberating Whatever You Meet: A Concise Instruction for Realizing
        the Nature of Mind'
      parent: Advice
    ae0ce1037dd842ef8aa0b5826149248c:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Advice
    71a3e50a80e44a0bb8bc32c38f243e95:
      title: The Mahāmudrā Practice of Stillness, Movement and Awareness
      parent: Advice
    476d292442424dbdab5dafb42fb01096:
      title: Instructions on the Fivefold Mahāmudrā
      parent: Advice
    c94591f448264cb28a72cc8fed7f2606:
      title: Pointing Out Instruction
      parent: Advice
    aaf80e5d4ec04f53892bb1d09f7536de:
      title: The Ganges Mahāmudrā Instructions
      parent: Advice
    a988ef3893934815908865c2b5e0e5b1:
      title: Aspiration of the Mahāmudrā of Definitive Meaning
      parent: Aspiration Prayers
    b3cbe7939be9470eb69396cc6b23bd31:
      title: 'A Casket of Sacred Dharma: Stages of Meditation on Dependent Arising'
      parent: Commentaries
    bdf1f47d699548608ca257845cfd7848:
      title: The Concise Mahāmudrā Preliminaries Arranged for Recitation
      parent: Preliminaries
    fc7c7801502149b7a33ab303a4b03bc7:
      title: 'The Excellent Path of Definitive Meaning: An Unmistaken Expression of
        the Definitive Mahāmudrā'
      parent: Songs
created_at: '2022-03-01T04:32:39.532474'
last_modified_at: '2022-03-01T04:32:39.532476'
